# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  i386: ghcr.io/home-assistant/i386-base:3.18
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: HAsync"
  org.opencontainers.image.description: "Advanced Home Assistant management interface with client pairing and entity synchronization"
  org.opencontainers.image.source: "https://github.com/xonatecnet/hasync"
  org.opencontainers.image.licenses: "MIT"
args:
  NODE_VERSION: "20"
